apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: duu29540b-go 
  janus-idp.io/tekton: duu29540b-go
  backstage.io/kubernetes-id: duu29540b-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: duu29540b-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml